Add `exclude` option
klauscfhq/hyper-pokemon pull request #55
Opened 2020-04-11 17:10 UTC by nasa9084

Fixes #54

## Summary

This PR adds a new option `exclude`, which is for exclude some pokemon themes from random or category.

2020-04-21 02:23 UTC, klaussinani commented on index.js
> +    },
```js
    get exclude() {
      const {exclude} = configObj;

      if (!exclude) {
        return [];
      }

      if (Array.isArray(exclude)) {
        return exclude;
      }

      return [exclude];
    },
```

2020-04-21 02:29 UTC, klaudiosinani requested changes
Great work, couple of tweaks and it is good to go
Also, the new `exclude` option must be added to the documentation; https://github.com/klaussinani/hyper-pokemon#options

2020-04-21 02:29 UTC, klaussinani commented on index.js
>  }
```js
function getRandomTheme(themes, category, exclude) {
  const keys = Object.keys(category).filter(key => !exclude.includes(key));

  if (keys.length > 0) {
    const index = Math.floor(Math.random() * (keys.length));
    const name = keys[index];
    return [name, category[name]];
  }

  // ALl themes filtered out thus resolve to default
  return ['pikachu', themes.pokemon.pikachu];
}
```

2020-04-21 02:29 UTC, klaussinani commented on index.js
>    const name = theme.trim().toLowerCase();
```js
  const name = theme.trim().toLowerCase();
  const excludedThemes = [...new Set(exclude)].map(x => x.trim().toLowerCase());
```

2020-04-21 02:29 UTC, klaussinani commented on index.js
> +    return getRandomTheme(themes[name], exclude);
```js
    return getRandomTheme(themes, themes.pokemon, excludedThemes);
```

2020-04-21 02:29 UTC, klaussinani commented on index.js
> +    return getRandomTheme(themes.pokemon, exclude);
```js
    return getRandomTheme(themes, themes[name], excludedThemes);
```

2020-04-22 04:19 UTC, nasa9084 commented
@klaussinani Thank you for your comments, I applied them, PTAL

2020-04-24 03:19 UTC, merged

2020-04-24 03:20 UTC, klaussinani commented
Looks great! Thank you a lot for taking the time to contribute!